[global]
log_level = "info"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[mode.packets.ics20_max_memo_size]
enabled = true
size = 32768

[mode.packets.ics20_max_receiver_size]
enabled = true
size = 2048

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[tracing_server]
enabled = false
port = 5555

[[chains]]
id = 'xion-testnet-1'
type = "CosmosSdk"
rpc_addr = 'https://rpc.xion-testnet-1.burnt.com:443'
grpc_addr = 'https://grpc.xion-testnet-1.burnt.com:443'
event_source = { mode = 'push', url = 'wss://websocket.xion-testnet-1.burnt.com/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'xion'
store_prefix='ibc'
key_name = 'xion_dev'
gas_price = { price = 0.1, denom = 'uxion' }

[[chains]]
id = 'injective-888'
ccv_consumer_chain = false
rpc_addr = 'https://k8s.testnet.tm.injective.network:443'
grpc_addr = 'https://k8s.testnet.chain.grpc.injective.network:443'
event_source = { mode = 'pull', interval = '800ms' }
rpc_timeout = '10s'
trusted_node = false
account_prefix = 'inj'
key_name = 'charlie'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 4000000
max_gas = 900000000
gas_price = { price = 700000000, denom = 'inj' }
gas_multiplier = 1.3
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '2', denominator = '3' }

